<a href="https://colab.research.google.com/github/MayureshOP-max/MachineLearning/blob/main/Day2_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np

In [24]:
a = np.array([90,34,89,23,50,120,67])
b = np.array([1,3,4,2,5,2,3])

In [25]:
ma, mb = a.mean(), b.mean()

In [26]:
sa, sb = a.std(), b.std()

In [27]:
scl_a = (a - ma) / sa
scl_b = (b - mb) / sb

In [28]:
(ma, sa), (scl_a.mean(), scl_a.std())

((67.57142857142857, 31.923377653630677), (7.335402126987641e-17, 1.0))

In [29]:
scl_a

array([ 0.70257514, -1.05162521,  0.67125013, -1.39620027, -0.55042511,
        1.64232532, -0.0179    ])

In [30]:
(mb, sb), (scl_b.mean(), scl_b.std())

((2.857142857142857, 1.2453996981544782), (-8.921435019309294e-17, 1.0))

In [31]:
from sklearn.preprocessing import StandardScaler
import pandas as pd

In [32]:
scl_std = StandardScaler()
df = pd.DataFrame({'a':a, 'b':b})
scl_std.fit(df)

StandardScaler()

In [33]:
print(scl_std.mean_)
print(scl_std.var_)

[67.57142857  2.85714286]
[1019.10204082    1.55102041]


In [34]:
print()

In [35]:
scl_std.transform(df)

array([[ 0.70257514, -1.49120227],
       [-1.05162521,  0.11470787],
       [ 0.67125013,  0.91766294],
       [-1.39620027, -0.6882472 ],
       [-0.55042511,  1.720618  ],
       [ 1.64232532, -0.6882472 ],
       [-0.0179    ,  0.11470787]])

# **MinMax Scaling**

In [36]:
a,b

(array([ 90,  34,  89,  23,  50, 120,  67]), array([1, 3, 4, 2, 5, 2, 3]))

In [37]:
mn_a, mn_b, mx_a, mx_b  = a.min(), b.min(), a.max(), b.max()
print(mn_a, mn_b, mx_a, mx_b)

23 1 120 5


In [39]:
scl_a = (a - mn_a) / (mx_a - mn_a)
print(scl_a)

[0.69072165 0.11340206 0.68041237 0.         0.27835052 1.
 0.45360825]


In [40]:
scl_b = (b - mn_b) / (mx_b - mn_b)
print(scl_b)

[0.   0.5  0.75 0.25 1.   0.25 0.5 ]


# **Concrete Dataset**

# **With Standard Scaling**

In [52]:
!pip install ucimlrepo
from ucimlrepo import fetch_ucirepo
import pandas as pd
import numpy as np
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.pipeline import Pipeline

In [47]:
concrete_compressive_strength = fetch_ucirepo(id=165)
X = concrete_compressive_strength.data.features
y = concrete_compressive_strength.data.targets

In [48]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=24)
lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
r2_score(y_test, y_pred)


0.5771752777048793

In [54]:
scl_std = StandardScaler()
pipe = Pipeline([('SCL', scl_std), ('LR', lr)])
pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_test)
r2_score(y_test, y_pred)

0.5771752777048791

0.5771752777048791

In [61]:
from ucimlrepo import fetch_ucirepo
import pandas as pd
import numpy as np
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.pipeline import Pipeline
from sklearn.linear_model import Ridge

In [62]:
concrete_compressive_strength = fetch_ucirepo(id=165)
X = concrete_compressive_strength.data.features
y = concrete_compressive_strength.data.targets

In [63]:
lr = LinearRegression()
lr.fit(X_train, y_train)
lr.intercept_, lr.coef_

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=24)
y_pred = lr.predict(X_test)
r2_score(y_test, y_pred)

0.5771752777048793

In [68]:
ridge = Ridge()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=24)
ridge.fit(X_train, y_train)
ridge.intercept_, ridge.coef_


(array([-35.44730826]),
 array([[ 0.12726534,  0.11257926,  0.09835178, -0.13691825,  0.23731065,
          0.0202036 ,  0.02616478,  0.12251103]]))

In [69]:
y_pred = lr.predict(X_test)
r2_score(y_test, y_pred)

0.5771752777048793